# Generated by Django 2.2 on 2021-02-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20210218_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='wall_message',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='login_app.User'),
        ),
    ]
